# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
np.show_config()

2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/_MY FOLDER/Apps/Anaconda/Library/include
    lib directory: C:/_MY FOLDER/Apps/Anaconda/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/_MY FOLDER/Apps/Anaconda/Library/include
    lib directory: C:/_MY FOLDER/Apps/Anaconda/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  cython:
    commands: cython
    linker: cython
 

#### 3. Create a null vector of size 10

In [3]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [4]:
print(f"{arr.size * arr.itemsize} bytes")

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [5]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [6]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49

In [7]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [8]:
arr = arr[::-1]
arr

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [11]:
res = np.nonzero([1,2,0,0,4,0])
print(res)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [12]:
id = np.eye(3)
id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [13]:
rand = np.random.random((3,3,3))
rand

array([[[0.76855057, 0.98786309, 0.20198118],
        [0.61431711, 0.8823998 , 0.76866368],
        [0.11836221, 0.53420653, 0.51084126]],

       [[0.4780303 , 0.72478338, 0.47530297],
        [0.58757667, 0.02789128, 0.12291091],
        [0.14142577, 0.72302663, 0.48147651]],

       [[0.95195806, 0.95804716, 0.94338159],
        [0.4873984 , 0.77022776, 0.70415416],
        [0.85245596, 0.14850237, 0.71912413]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [19]:
rand = np.random.random((10,10))
print(rand)
print(rand.min())
print(rand.max())

[[0.17089476 0.53848481 0.10697339 0.8399334  0.62385948 0.64471062
  0.67827208 0.39233166 0.69411105 0.17791018]
 [0.79286046 0.60673374 0.45660655 0.82624237 0.55193183 0.67476296
  0.54776335 0.5523707  0.18237573 0.17635217]
 [0.85791354 0.91672095 0.94438602 0.96292244 0.32062587 0.00817104
  0.52746926 0.21725088 0.20719026 0.07159994]
 [0.02556526 0.67713725 0.57460171 0.39436563 0.76364895 0.53571806
  0.28491379 0.92474364 0.28064364 0.68594173]
 [0.69594124 0.83797063 0.08230014 0.51209319 0.9072601  0.6337044
  0.41396312 0.13102331 0.2111759  0.78142448]
 [0.3320879  0.00527566 0.19796405 0.41029968 0.00862171 0.40069707
  0.74918487 0.68758425 0.10535992 0.49023695]
 [0.51675735 0.34120316 0.21059836 0.22922574 0.77156182 0.97387644
  0.690575   0.91913429 0.31155416 0.14638151]
 [0.19048456 0.56847365 0.74289858 0.76001538 0.68952621 0.39724445
  0.40508303 0.70927497 0.69608042 0.62829405]
 [0.87072887 0.3324486  0.93908461 0.85726509 0.81146598 0.35033765
  0.65550344 

#### 14. Create a random vector of size 30 and find the mean value

In [20]:
arr = np.random.random(30)
print(arr)
print(arr.mean())

[0.93873133 0.48190912 0.93730399 0.02293956 0.41354563 0.04821542
 0.55146323 0.60804312 0.47331561 0.73320807 0.49342173 0.65336322
 0.33197449 0.45986477 0.01175514 0.1018154  0.22679627 0.55700432
 0.90605641 0.72816516 0.96766407 0.57419633 0.86810345 0.2735838
 0.71222138 0.41336564 0.36328909 0.8311252  0.04607864 0.60159413]
0.5110037900506798


#### 15. Create a 2d array with 1 on the border and 0 inside

In [21]:
arr = np.ones((4,4))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [22]:
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [23]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [24]:
arr = np.diag(1+np.arange(4),k=-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [25]:
arr = np.zeros((8,8), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [26]:
print(np.unravel_index(100,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(4))
